site_name: Huaizhou Li
site_url: https://huaizhouli.github.io/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    primary: blue

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.magiclink

# Optional: Add this if you want to include extra CSS
# extra_css:
#   - stylesheets/extra.css
